# Use the specified base image
FROM nvcr.io/nvidia/pytorch:19.04-py3

RUN apt-get -y update

RUN apt-get install -y python3-pip software-properties-common wget ffmpeg

RUN mkdir -p /root/.torch/models

RUN mkdir -p /data/models

WORKDIR /data/models

# Download the .bin files
RUN curl -k -o ColorizeArtistic_gen.pth 'https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth'

RUN curl -k -o ColorizeStable_gen.pth 'https://www.dropbox.com/s/mz5n9hiq6hmwjq7/ColorizeStable_PretrainOnly_gen.pth?dl=1'

# Go back to the /data directory
ADD . /data/

WORKDIR /data

RUN pip install --upgrade pip

# Multiple RUN instructions for pip
RUN pip3 install -r requirements.txt opencv-python Flask Pillow scikit-image requests flask-cors

# Expose port 5000
EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]
