From nvcr.io/nvidia/pytorch:19.04-py3

RUN apt-get -y update

RUN apt-get install -y python3-pip software-properties-common wget ffmpeg

RUN mkdir -p /root/.torch/models

RUN mkdir -p /data/models

ADD . /data/

WORKDIR /data

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

RUN pip3 install opencv-python

RUN pip3 install Flask

RUN pip3 install Pillow

RUN pip3 install scikit-image

RUN pip3 install requests

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]

