From nvcr.io/nvidia/pytorch:19.04-py3

RUN apt-get -y update

RUN apt-get install -y python3-pip software-properties-common wget ffmpeg

RUN mkdir -p /root/.torch/models

RUN mkdir -p /data/models

WORKDIR /data/models

# Download the .bin files
RUN curl -k -o ColorizeArtistic_gen.pth 'https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth'

RUN curl -k -o ColorizeStable_gen.pth 'https://www.dropbox.com/s/mz5n9hiq6hmwjq7/ColorizeStable_PretrainOnly_gen.pth?dl=1'



ADD . /data/

WORKDIR /data

RUN pip install --upgrade pip

RUN pip3 install -r requirements.txt

RUN pip3 install opencv-python

RUN pip3 install Flask

RUN pip3 install Pillow

RUN pip3 install scikit-image

RUN pip3 install requests

RUN pip3 install flask-cors

EXPOSE 5000

ENTRYPOINT ["python3"]

CMD ["app.py"]

